apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector: # nodeSelector 추가
        kubernetes.io/hostname: worker2   # 원하는 노드 이름 지정
      containers:
        - name: backend-pod
          image: 119.197.27.55:5000/backend@sha256:dca72bbdfa7bd1dafffe4e1854da63099500f7cd05b34e331bcd5ea0ea86e81b
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 31500
