apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-pod
          image: 119.197.27.55:5000/backend@sha256:7cf35bfafbdf2a78ae5407f082c454f33255d9a821422dc0a89896182fa27b4e
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 31500
