name: final project backendpart CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean build
      
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Configure Docker daemon
        run: |
          echo '{ "insecure-registries": ["180.150.207.73:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Login to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 180.150.207.73:5000
      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            180.150.207.73:5000/backend:${{ github.sha }}
            180.150.207.73:5000/backend:latest
      - name: Save image digest
        run: |
          echo "${{ steps.docker_build.outputs.digest }}" > image-digest.txt
          IMAGE_DIGEST_SHORT=$(cat image-digest.txt | cut -c 1-5)
          echo $IMAGE_DIGEST_SHORT > image-digest-short.txt
      - name: Upload image digest as artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-digest-short
          path: image-digest-short.txt

  update-manifest:
    name: Update Kubernetes manifest
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download image digest artifact
        uses: actions/download-artifact@v2
        with:
          name: image-digest-short
      - name: Update image in Kubernetes manifest
        run: |
          IMAGE_DIGEST_SHORT=$(cat image-digest-short.txt)
          sed -i "s|image: 180.150.207.73:5000/backend|image: 180.150.207.73:5000/backend@$IMAGE_DIGEST_SHORT|g" deploy/deployment.yml
      - name: Commit and push changes
        run: |
          git config --local user.email "mastgm0817@gmail.com"
          git config --local user.name "mastgm0817"
          git add deploy/deployment.yml
          git commit -m "Update image in Kubernetes manifest"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mastgm0817/final_backend.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
