name: final project backendpart CI/CD with Gradle

on:
  push:
    branches: [ "main", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      KAKAO_ADMIN_KEY: ${{ secrets.KAKAO_ADMIN_KEY }}
      WEB_URL : ${{ secrets.WEB_URL }}


    steps:
    - uses: actions/checkout@v3

    - name: Setup Google Cloud credentials
      run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > service-account.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json


    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean build -PDATABASE_HOST=${{ secrets.DATABASE_HOST }} -PDATABASE_NAME=${{ secrets.DATABASE_NAME }} -PDATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -PDATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

    - name: Configure Docker daemon
      run: |
        echo '{ "insecure-registries": ["119.197.27.55:5000"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
    - name: Login to Docker registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 119.197.27.55:5000
    - name: Build and Push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          119.197.27.55:5000/backend:${{ github.sha }}
          119.197.27.55:5000/backend:latest
          
    - name: Save image digest
      run: echo "${{ steps.docker_build.outputs.digest }}" > image-digest.txt
    - name: Upload image digest as artifact
      uses: actions/upload-artifact@v2
      with:
        name: image-digest
        path: image-digest.txt

  update-manifest:
    name: Update Kubernetes manifest
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Download image digest artifact
          uses: actions/download-artifact@v2
          with:
            name: image-digest
        - name: Update image in Kubernetes manifest
          run: |
            IMAGE_DIGEST=$(cat image-digest.txt)
            sed -i "s|image: 119.197.27.55:5000/backend@sha256:[a-zA-Z0-9]*|image: 119.197.27.55:5000/backend@$IMAGE_DIGEST|g" deploy/deployment.yml
        - name: Commit and push changes
          run: |
            git config --local user.email "mastgm0817@gmail.com"
            git config --local user.name "mastgm0817"
            git add deploy/deployment.yml
            git commit -m "Update image in Kubernetes manifest"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mastgm0817/final_backend.git HEAD:main
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

  slack_push_alarm:
    runs-on: ubuntu-latest
    needs: ["update-manifest"]
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
         
     - name: action-slack
       uses: 8398a7/action-slack@v3
       with:
         status: ${{ job.status }}
         author_name: Frontend - production
         fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
         mention: here
         if_mention: failure,cancelled
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
       if: success()
